import type {
  Lead,
  Company,
  Campaign,
  Opportunity,
  ResearchFinding,
  Interaction,
  AIInsight,
} from './types'

export const mockCampaigns: Campaign[] = [
  {
    campaign_id: 'camp_001',
    name: 'Anchor Clients',
    description: 'Quarterly strategic check-ins with top active clients to deepen the relationship and surface new pipeline.',
    target_segment: 'Existing top clients sending consistent work',
    location: 'Miami, New York, France',
    project_types: 'Luxury residential, luxury hospitality, competitions',
    cta: 'Set a discovery meeting',
    channels: ['Email'],
    cadence: 'Quarterly',
    status: 'Active',
    owner: 'Demian',
    notes: 'Focus on understanding pipeline and strengthening trust. Not a sales push.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
  {
    campaign_id: 'camp_002',
    name: 'Past Events Leads',
    description: 'Reconnect with leads met in person at 2026 events while the relationship is still warm.',
    target_segment: 'Leads met at 2026 events',
    cta: 'Set a discovery meeting',
    channels: ['Email', 'LinkedIn'],
    cadence: 'Weekly',
    status: 'Active',
    owner: 'Demian',
    notes: 'Personalize every touchpoint — reference the specific event and conversation.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
  {
    campaign_id: 'camp_003',
    name: 'Past Clients Rekindling',
    description: "Re-engage past clients who stopped sending work. Show Oaki's upgraded capabilities and address pricing concerns.",
    target_segment: 'Past clients, stopped sending work',
    location: 'New York, Miami',
    project_types: 'Luxury residential',
    offer: "Oaki's upgraded capabilities and new portfolio",
    pain_point: 'Pricing was a concern',
    cta: 'Set a discovery meeting',
    channels: ['Email'],
    cadence: 'Weekly',
    status: 'Active',
    owner: 'Demian',
    notes: 'Lead with quality and new work. Address pricing indirectly by showing value.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
  {
    campaign_id: 'camp_004',
    name: 'Outreach Campaign',
    description: 'Cold outreach to high-fit architects, interior designers, and developers in New York.',
    target_segment: 'Architects, interior designers, real estate developers',
    location: 'New York',
    project_types: 'Luxury residential, hospitality',
    offer: 'Create a visual narrative for architectural projects with an editorial look',
    pain_point: 'Need to excel in a competitive global market to win work, investment, and attention',
    cta: 'Set a discovery meeting',
    channels: ['Letter', 'Email', 'LinkedIn'],
    cadence: 'Twice weekly',
    status: 'Active',
    owner: 'Demian',
    notes: 'Tuesdays and Thursdays only. Research-first — only contact when there is a real signal.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
]

export const mockCompanies: Company[] = [
  {
    company_id: 'co_001',
    company_name: 'Studio Aria',
    website: 'https://studioaria.com',
    linkedin_company_url: 'https://linkedin.com/company/studio-aria',
    industry: 'Architecture',
    location: 'New York, NY',
    company_size: '10-50',
    project_type: 'Luxury Residential, Hospitality',
    ideal_client_fit: true,
    fit_reason: 'Strong portfolio of luxury residential and boutique hospitality. Editorial visual identity.',
    design_quality_score: 9,
    visual_identity_score: 8,
    brand_positioning: 'High-end residential and hospitality studio with a refined, editorial aesthetic',
    architectural_style: 'Contemporary, materiality-driven',
    market_position: 'Premium',
    project_scale: 'Mid to large',
    known_projects: 'The Reef Residences, Hotel Mira Miami',
    notes: 'Featured in Architectural Digest 2025. Recently expanded to hospitality.',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-04-22T00:00:00Z',
  },
  {
    company_id: 'co_002',
    company_name: 'Maison Peralta',
    website: 'https://maisonperalta.com',
    linkedin_company_url: 'https://linkedin.com/company/maison-peralta',
    industry: 'Interior Design',
    location: 'Miami, FL',
    company_size: '5-20',
    project_type: 'Luxury Residential',
    ideal_client_fit: true,
    fit_reason: 'Boutique luxury interior design firm. Clients are high-net-worth individuals.',
    design_quality_score: 9,
    visual_identity_score: 9,
    brand_positioning: 'Curated luxury interiors for discerning clients',
    architectural_style: 'Transitional, refined',
    market_position: 'Ultra-premium',
    project_scale: 'Residential',
    known_projects: 'Private residences in Brickell and Palm Beach',
    notes: 'Past client. Worked on two projects in 2023. Pricing was a concern.',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
  {
    company_id: 'co_003',
    company_name: 'Vero Architecture',
    website: 'https://veroarch.com',
    linkedin_company_url: 'https://linkedin.com/company/vero-architecture',
    industry: 'Architecture',
    location: 'New York, NY',
    company_size: '20-100',
    project_type: 'Competition, Luxury Residential',
    ideal_client_fit: true,
    fit_reason: 'Strong competition portfolio. Needs high-quality visuals to win international bids.',
    design_quality_score: 8,
    visual_identity_score: 7,
    brand_positioning: 'Competition-first architecture firm expanding into luxury residential',
    architectural_style: 'Parametric, concept-driven',
    market_position: 'Premium',
    project_scale: 'Large',
    known_projects: 'Dubai Cultural Center competition, Manhattan residential tower',
    notes: 'Met at AIANY Gala in March 2026. Expressed interest in competition visualization.',
    created_at: '2026-03-20T00:00:00Z',
    updated_at: '2026-05-10T00:00:00Z',
  },
  {
    company_id: 'co_004',
    company_name: 'Côte Développement',
    website: 'https://cotedeveloppement.fr',
    linkedin_company_url: 'https://linkedin.com/company/cote-developpement',
    industry: 'Real Estate Development',
    location: 'Paris, France',
    company_size: '10-50',
    project_type: 'Luxury Residential, Hospitality',
    ideal_client_fit: true,
    fit_reason: 'French luxury developer with international projects. Strong visual narrative needs.',
    design_quality_score: 8,
    visual_identity_score: 8,
    brand_positioning: 'Lifestyle-forward luxury real estate developer',
    architectural_style: 'Contemporary European',
    market_position: 'Premium',
    project_scale: 'Large',
    known_projects: 'Résidence Lumière, Le Mas Saint-Tropez',
    notes: 'Anchor client. Quarterly check-in due.',
    created_at: '2025-08-01T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
]

export const mockLeads: Lead[] = [
  {
    lead_id: 'lead_001',
    company_id: 'co_001',
    first_name: 'Sofia',
    last_name: 'Marchetti',
    full_name: 'Sofia Marchetti',
    email: 'sofia@studioaria.com',
    linkedin_url: 'https://linkedin.com/in/sofia-marchetti',
    linkedin_connection_status: 'Connection Ready',
    linkedin_dm_status: 'DM Ready',
    linkedin_warmth: 'Aware',
    last_linkedin_touch_date: '2026-05-03',
    linkedin_notes: 'Good candidate for a low-friction connection note tied to Studio Aria hospitality momentum.',
    title: 'Principal Architect',
    company_name: 'Studio Aria',
    website: 'https://studioaria.com',
    location: 'New York, NY',
    campaign_id: 'camp_004',
    source: 'Outreach Campaign',
    pipeline_stage: 'Contacted',
    lead_status: 'Active',
    business_fit_score: 9,
    taste_score: 9,
    relationship_score: 3,
    opportunity_score: 8,
    priority_score: 8,
    relationship_temperature: 'Warm',
    last_touch_date: '2026-05-05',
    next_followup_date: '2026-05-22',
    next_action: 'Send follow-up referencing their new hospitality project',
    known_pain_points: 'Current visualization vendor lacks editorial quality',
    preferred_communication_style: 'Email, direct and visual',
    owner: 'Demian',
    notes: 'AD feature in Jan 2026. Recently launched Hotel Mira Miami project.',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-05-05T00:00:00Z',
  },
  {
    lead_id: 'lead_002',
    company_id: 'co_002',
    first_name: 'Valentina',
    last_name: 'Peralta',
    full_name: 'Valentina Peralta',
    email: 'valentina@maisonperalta.com',
    linkedin_url: 'https://linkedin.com/in/valentina-peralta',
    linkedin_connection_status: 'Connected',
    linkedin_dm_status: 'Not Started',
    linkedin_warmth: 'Warm',
    last_linkedin_touch_date: '2025-11-15',
    linkedin_notes: 'Past client. Use LinkedIn softly; email is likely better for the first rekindling touch.',
    title: 'Founder & Creative Director',
    company_name: 'Maison Peralta',
    website: 'https://maisonperalta.com',
    location: 'Miami, FL',
    campaign_id: 'camp_003',
    source: 'Past Client',
    pipeline_stage: 'Dormant',
    lead_status: 'Active',
    business_fit_score: 9,
    taste_score: 9,
    relationship_score: 7,
    opportunity_score: 7,
    priority_score: 8,
    relationship_temperature: 'Cool',
    last_touch_date: '2025-11-15',
    last_meaningful_touch: '2025-09-10',
    next_followup_date: '2026-05-20',
    next_action: 'Re-engage with portfolio update — show new capabilities',
    known_pain_points: 'Previous pricing concern, needed faster turnaround',
    preferred_communication_style: 'Personal, thoughtful email',
    owner: 'Demian',
    notes: 'Worked together in 2023. Relationship cooled after pricing feedback. High-value rekindling opportunity.',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
  {
    lead_id: 'lead_003',
    company_id: 'co_003',
    first_name: 'Marcus',
    last_name: 'Webb',
    full_name: 'Marcus Webb',
    email: 'marcus@veroarch.com',
    linkedin_url: 'https://linkedin.com/in/marcus-webb-arch',
    linkedin_connection_status: 'Connected',
    linkedin_dm_status: 'Replied',
    linkedin_warmth: 'Engaged',
    last_linkedin_touch_date: '2026-03-25',
    linkedin_notes: 'Manual connection note sent after AIANY Gala. Keep LinkedIn supportive; current active thread is email.',
    title: 'Design Director',
    company_name: 'Vero Architecture',
    website: 'https://veroarch.com',
    location: 'New York, NY',
    campaign_id: 'camp_002',
    source: 'AIANY Gala 2026',
    pipeline_stage: 'Replied',
    lead_status: 'Active',
    business_fit_score: 8,
    taste_score: 8,
    relationship_score: 5,
    opportunity_score: 9,
    priority_score: 9,
    relationship_temperature: 'Warm',
    last_touch_date: '2026-05-12',
    last_meaningful_touch: '2026-05-12',
    next_followup_date: '2026-05-21',
    next_action: 'Propose discovery call — reference Dubai competition timeline',
    known_pain_points: 'Needs fast turnaround for competition submissions, current vendor misses deadlines',
    preferred_communication_style: 'Email with portfolio visuals',
    owner: 'Demian',
    notes: 'Met at AIANY Gala March 2026. Strong chemistry. Dubai competition deadline approaching in July.',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-05-12T00:00:00Z',
  },
  {
    lead_id: 'lead_004',
    company_id: 'co_004',
    first_name: 'Élodie',
    last_name: 'Fontaine',
    full_name: 'Élodie Fontaine',
    email: 'elodie@cotedeveloppement.fr',
    linkedin_url: 'https://linkedin.com/in/elodie-fontaine',
    linkedin_connection_status: 'Connected',
    linkedin_dm_status: 'Unknown',
    linkedin_warmth: 'Active',
    last_linkedin_touch_date: '2026-02-18',
    linkedin_notes: 'Anchor relationship. LinkedIn is context, not the primary channel.',
    title: 'Head of Development',
    company_name: 'Côte Développement',
    website: 'https://cotedeveloppement.fr',
    location: 'Paris, France',
    campaign_id: 'camp_001',
    source: 'Anchor Client',
    pipeline_stage: 'Nurture',
    lead_status: 'Active',
    business_fit_score: 10,
    taste_score: 9,
    relationship_score: 9,
    opportunity_score: 7,
    priority_score: 9,
    relationship_temperature: 'Warm',
    last_touch_date: '2026-02-18',
    last_meaningful_touch: '2026-02-18',
    next_followup_date: '2026-05-18',
    next_action: 'Quarterly check-in — ask about new projects, share recent work',
    known_pain_points: 'Needs visuals that match their lifestyle-forward brand direction',
    preferred_communication_style: 'Formal email in French or English',
    owner: 'Demian',
    notes: 'Anchor client. Sends consistent work. Quarterly strategic check-in overdue.',
    created_at: '2025-08-05T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
]

export const mockOpportunities: Opportunity[] = [
  {
    opportunity_id: 'opp_001',
    company_id: 'co_003',
    lead_id: 'lead_003',
    opportunity_type: 'Competition Deadline',
    source: 'Manual Research',
    summary: 'Dubai Cultural Center competition submission deadline is July 2026. Vero needs final visuals by late June.',
    why_now: 'Competition deadline in 6 weeks. Marcus replied and expressed urgency. Window to convert is narrow.',
    recommended_action: 'Propose discovery call this week to scope the competition package.',
    urgency: 'High',
    confidence: 88,
    status: 'Open',
    created_at: '2026-05-12T00:00:00Z',
    updated_at: '2026-05-12T00:00:00Z',
  },
  {
    opportunity_id: 'opp_002',
    company_id: 'co_002',
    lead_id: 'lead_002',
    opportunity_type: 'Past Client Rekindling',
    source: 'Research',
    summary: 'Maison Peralta launched two new residential projects in Brickell in Q1 2026. Valentina active on LinkedIn.',
    why_now: "Relationship has been dormant 6 months. New project launches signal active pipeline. Oaki's upgraded portfolio directly addresses previous quality concern.",
    recommended_action: 'Send a personal email with 2-3 recent portfolio images that reflect Maison Peralta\'s aesthetic direction.',
    urgency: 'Medium',
    confidence: 72,
    status: 'Open',
    created_at: '2026-05-08T00:00:00Z',
    updated_at: '2026-05-08T00:00:00Z',
  },
  {
    opportunity_id: 'opp_003',
    company_id: 'co_004',
    lead_id: 'lead_004',
    opportunity_type: 'Anchor Client Check-in',
    source: 'Calendar',
    summary: 'Quarterly check-in with Côte Développement is overdue. Last meaningful touch was February 2026.',
    why_now: "Q2 strategic window. Élodie's team likely in planning for second-half projects. Check-in maintains relationship health and surfaces new pipeline.",
    recommended_action: 'Send a warm check-in email asking about their H2 pipeline and share 1-2 relevant new pieces.',
    urgency: 'Medium',
    confidence: 90,
    status: 'Open',
    created_at: '2026-05-15T00:00:00Z',
    updated_at: '2026-05-15T00:00:00Z',
  },
]

export const mockResearchFindings: ResearchFinding[] = [
  {
    finding_id: 'rf_001',
    company_id: 'co_001',
    lead_id: 'lead_001',
    source_type: 'Press',
    source_url: 'https://architecturaldigest.com/studio-aria',
    research_summary: 'Studio Aria featured in Architectural Digest January 2026 for Hotel Mira Miami. Strong editorial photography.',
    design_observations: 'Warm material palette, indoor-outdoor blur, layered textiles. Highly photogenic.',
    market_positioning: 'Positioned as hospitality-forward luxury studio expanding from residential.',
    visual_identity_notes: 'Their own brand photography is excellent — sets a high bar for visualization quality.',
    signals_detected: 'New hospitality vertical, press momentum, visual quality bar is high',
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    finding_id: 'rf_002',
    company_id: 'co_003',
    lead_id: 'lead_003',
    source_type: 'LinkedIn',
    source_url: 'https://linkedin.com/company/vero-architecture/posts',
    research_summary: 'Marcus Webb posted about Dubai Cultural Center competition shortlist. Submission deadline July 31 2026.',
    design_observations: 'Competition imagery currently uses generic 3D renders — significant quality gap vs their design ambition.',
    market_positioning: 'Competing for international cultural commissions alongside top-tier firms.',
    visual_identity_notes: 'LinkedIn posts show strong design narrative but weak visualization support.',
    signals_detected: 'Competition deadline, quality gap in current visuals, high-stakes submission',
    created_at: '2026-05-11T00:00:00Z',
  },
]

export const mockInteractions: Interaction[] = [
  {
    interaction_id: 'int_001',
    lead_id: 'lead_001',
    company_id: 'co_001',
    channel: 'Email',
    direction: 'Outbound',
    subject: 'Visual narratives for Studio Aria',
    body_summary: 'Introduced Oaki, referenced AD feature and Hotel Mira. Offered to share relevant portfolio.',
    sent_at: '2026-05-05T10:00:00Z',
    created_at: '2026-05-05T10:00:00Z',
  },
  {
    interaction_id: 'int_002',
    lead_id: 'lead_003',
    company_id: 'co_003',
    channel: 'LinkedIn',
    direction: 'Outbound',
    subject: 'Connection note after AIANY Gala',
    body_summary: 'Referenced meeting at the Gala. Mentioned Oaki\'s competition visualization work.',
    linkedin_manual_status: 'Sent',
    sent_at: '2026-03-25T14:00:00Z',
    created_at: '2026-03-25T14:00:00Z',
  },
  {
    interaction_id: 'int_003',
    lead_id: 'lead_003',
    company_id: 'co_003',
    channel: 'Email',
    direction: 'Inbound',
    subject: 'Re: Competition visualization',
    body_summary: "Marcus replied expressing interest. Mentioned Dubai competition deadline. Asked about Oaki's competition portfolio.",
    sent_at: '2026-05-12T09:30:00Z',
    created_at: '2026-05-12T09:30:00Z',
  },
]

export const mockAIInsights: AIInsight[] = [
  {
    insight_id: 'ai_001',
    lead_id: 'lead_003',
    company_id: 'co_003',
    opportunity_id: 'opp_001',
    summary: 'Marcus Webb at Vero Architecture is a high-priority opportunity. Active competition deadline creates genuine urgency. Warm personal connection from AIANY Gala. Current visualization quality is clearly below their design ambition.',
    why_now: 'Dubai Cultural Center submission due July 31. Marcus already replied expressing interest. 6-week window to convert before the opportunity closes.',
    intent_level: 'high',
    recommended_next_action: 'Send a short email this week proposing a 20-min discovery call to scope the Dubai competition package. Reference his reply and the timeline.',
    suggested_email: `Subject: Dubai competition — 20 minutes this week?\n\nHi Marcus,\n\nThank you for your reply. Given the July deadline for the Dubai Cultural Center, I think timing is right for a quick conversation.\n\nWould you have 20 minutes this week to walk through the submission scope and how we might support it?\n\nI'll share a few competition references ahead of time so you have context.\n\nBest,\nDemian`,
    suggested_linkedin_dm: "Marcus — following up on your email. Happy to connect over the Dubai competition timeline whenever works for you.",
    discovery_questions: [
      "What's the submission date and what deliverables does the competition require?",
      "How many images are typically in your competition boards?",
      "What's your current visualization workflow — do you have a team or outsource?",
      "What's the biggest gap between your design intent and what your current renders show?",
    ],
    objections: [
      'Timeline too tight',
      'Budget not confirmed yet',
      'Already working with another studio',
    ],
    opportunities: [
      'Competition to residential pipeline — if Dubai goes well, position for upcoming Manhattan project',
      'Multi-project relationship if quality meets their standard',
    ],
    risk_level: 'low',
    confidence: 88,
    created_at: '2026-05-14T00:00:00Z',
  },
]
